[project]
name = "mass"
version = "6.1.0"
description = "Metadata Artifact Search Service - A service for searching metadata artifacts and filtering results."
dependencies = [
    "typer>=0.19",
    "ghga-service-commons[api]>=7",
    "ghga-event-schemas~=10.1",
    "hexkit[mongodb,akafka]>=8.1",
]

[project.urls]
Repository = "https://github.com/ghga-de/mass"

[project.scripts]
mass = "mass.__main__:cli"
